# Intro Numpy

E' una libreria Python per il calcolo scientifico che permette di ottenere buone performance dal punto di vista computazionale pur mantenendo una sintassi semplice come quella di python.

In [8]:
import numpy as np

# Numpy Array

Alla base di Numpy vi sono gli array Numpy, oggetti che rappresentano array multidimensionali, ottimizzati per il calcolo scientifico.

Utilizzare gli array di Numpy consente l'utlizzo di funzioni matematiche scritte in C e spesso semplifica la sintassi.

Ipotiziamo di avere due matrici A e B, e di volerne sommare gli elementi uno ad uno

In [9]:
A = [[1,2,3,4], [5,6,7,8]]
B = [[-1,-2,-3,-4], [-5,-6,-7,-8]]

C = [[a + b for a, b in zip(A_i, B_i)] for A_i, B_i in zip(A, B)]
print(C)

# In Alternativa
#C = []
#for A_i, B_i in zip(A, B):
#  C_i = []
#  for a_i, b_i in zip(A_i, B_i):
#    C_i.append(a_i + b_i)
#  C.append(C_i)
#print(C)


[[0, 0, 0, 0], [0, 0, 0, 0]]


In [10]:
A_array = np.array(A)
B_array = np.array(B)

C_array = A_array + B_array
print(C_array)

[[0 0 0 0]
 [0 0 0 0]]


E se ora avessi bisogno di lavorare con tensori di 3 dimensioni?

In [11]:
A_array = np.array([[[1,2,3]], [[4,5,6]], [[7,8,9]]])
B_array = np.array([[[-1,-2,-3]], [[-4,-5,-6]], [[-7,-8,-9]]])

C_array = A_array + B_array
print(C_array)

[[[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]]


Come possiamo vedere, utilizzando numpy non dobbiamo modificare il codice che produce la somma dei tensori. Invece con l'altro metodo avremmo dovuto modificare il codice per considerare la nuova dimensione non presente prima.

## Quanto veloce e' numpy rispetto ad un ciclo for in Python?

Proviamo a calcolare il prodotto scalare di due vettori

In [12]:
import time

In [13]:
l1 = [float(d) for d in range(100000)]
l2 = [float(d) for d in range(100000)]
l1_array = np.array(l1)
l2_array = np.array(l2)

In [14]:
%%timeit
s = 0
for l1_i, l2_i in zip(l1, l2): s += l1_i * l2_i

9.13 ms ± 717 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
%%timeit
s = np.dot(l1_array, l2_array)

296 μs ± 10.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Come creare Numpy Array

Vi sono diversi modi per creare degli array in Numpy. Se abbiamo il nostro vettore rappresentato in una normale lista possiamo trasformarlo in un numpy array come abbiamo visto negli esempi precedenti.

In [16]:
vec = [1,2,3,4,5]
vec_array = np.array(vec)

In [17]:
vec_array

array([1, 2, 3, 4, 5])

Spesso e' necessario generare degli array con determinate carattersitche, ad esempio tutti i numeri in un certo range

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.zeros_like(vec_array)

array([0, 0, 0, 0, 0])

In [23]:
np.ones_like(vec_array)

array([1, 1, 1, 1, 1])

# Accedere ad un Numpy Array
Per accedere agli elementi di un array numpy segue le solite regole di python a cui siamo abituati con le liste

In [24]:
a = np.arange(20)

Per acceredere all'$i$-esimo elemento utilizziamo la notazione `a[i]`

In [25]:
print(f'a = {a}')
print(f'a[0] = {a[0]}')
print(f'a[-1] = {a[-1]}')

a = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[0] = 0
a[-1] = 19


Possiamo anche utilizzare delle slice, ad esempio per accedere agli elementi dal $i$-esimo al $j$-esimo (escluso) `a[i:j]`

In [26]:
print(f'a[1:5] = {a[1:5]}')
print(f'a[1:] = {a[1:]}')
print(f'a[:-1] = {a[:-1]}')
print(f'a[-10:-2] = {a[-10:-2]}')

a[1:5] = [1 2 3 4]
a[1:] = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[:-1] = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
a[-10:-2] = [10 11 12 13 14 15 16 17]


E' anche possibile selezionare degli elementi di un array utlizzando delle espressioni booleane, vediamo degli esempi

In [27]:
a = np.arange(20)
np.random.shuffle(a)
print(a)

[ 7  0 10 13  8  5  9  3  2 15 12  6  1 11 16 18 17 14  4 19]


In [28]:
a[a > 7.5]

array([10, 13,  8,  9, 15, 12, 11, 16, 18, 17, 14, 19])

In [29]:
a[(a > 7.5) & (a < 10)]

array([8, 9])

Come funziona questa cosa?

In [30]:
b = a > 7.5
c = a < 10
d = (b & c)
print(f'b = {b}')
print(f'c = {c}')
print(f'd = {d}')

b = [False False  True  True  True False  True False False  True  True False
 False  True  True  True  True  True False  True]
c = [ True  True False False  True  True  True  True  True False False  True
  True False False False False False  True False]
d = [False False False False  True False  True False False False False False
 False False False False False False False False]


In [31]:
a[d]

array([8, 9])

# Operazioni con Numpy Array

In [32]:
a = np.array([1,2,3,4,5])

Modificare un elemento

In [33]:
a[0] = 25
a[-2] = 9
print(a)

[25  2  3  9  5]


Tipicamente le operazioni matematiche su numpy array vengono applicate elemento per elemento

In [34]:
b = a * 2
print(b)

[50  4  6 18 10]


In [35]:
print(f'a + b : {a + b }')
print(f'a - b : {a - b }')
print(f'a * b : {a * b }')
print(f'a / b : {a / b }')
print(f'a ** b: {a ** b}')
print(f'a % b : {a % b }')
print(f'a % b : {a % b }')

a + b : [75  6  9 27 15]
a - b : [-25  -2  -3  -9  -5]
a * b : [1250    8   18  162   50]
a / b : [0.5 0.5 0.5 0.5 0.5]
a ** b: [-3842938066129721103                   16                  729
   150094635296999121              9765625]
a % b : [25  2  3  9  5]
a % b : [25  2  3  9  5]


Le precedenti operazioni sono anche definite come funzioni di numpy

In [36]:
print(f'np.add(a, b): {np.add(a, b)}')
print(f'np.subtract(a, b): {np.subtract(a, b)}')
print(f'np.multiply(a, b): {np.multiply(a, b)}')
print(f'np.divide(a, b): {np.divide(a, b)}')
print(f'np.power(a, b): {np.power(a, b)}')
print(f'np.mod(a, b): {np.mod(a, b)}')
print(f'np.mod(b, a): {np.mod(b, a)}')

np.add(a, b): [75  6  9 27 15]
np.subtract(a, b): [-25  -2  -3  -9  -5]
np.multiply(a, b): [1250    8   18  162   50]
np.divide(a, b): [0.5 0.5 0.5 0.5 0.5]
np.power(a, b): [-3842938066129721103                   16                  729
   150094635296999121              9765625]
np.mod(a, b): [25  2  3  9  5]
np.mod(b, a): [0 0 0 0 0]


E molte altre funzioni matematiche sono presenti

In [37]:
print(f'np.log(a): {np.log(a)}')
print(f'np.sqrt(a): {np.sqrt(a)}')
# alcune operazioni possono anche essere applicate su tutti gli elementi del array
print(f'np.sum(a): {np.sum(a)}')
print(f'np.prod(a): {np.prod(a)}')

np.log(a): [3.21887582 0.69314718 1.09861229 2.19722458 1.60943791]
np.sqrt(a): [5.         1.41421356 1.73205081 3.         2.23606798]
np.sum(a): 44
np.prod(a): 6750


## Operazioni su array booleani

Un'importante proprieta' degli array di valori booleani e' il fatto che i valori `True` e `False` vengono automaticamente convertiti in $1$ e $0$ quando presenti in un'operazione matematica

In [38]:
b_array = np.array([True, False, False, False, True, True])

In [39]:
np.sum(b_array)

np.int64(3)

In [40]:
np.prod(b_array)

np.int64(0)

In [41]:
print(f'~b_array = {~b_array}')
np.sum(~b_array)

~b_array = [False  True  True  True False False]


np.int64(3)

In [42]:
c_array = np.array([True, False, True, False, False, True])

In [43]:
b_array + c_array

array([ True, False,  True, False,  True,  True])

In [44]:
b_array * c_array

array([ True, False, False, False, False,  True])

## Esercizio
Un' azienda che produce macchinari agricoli utilizza 27 diversi tipi di materie prime. Il costo unitario di ogni materia prima e' salvato in un numpy array e a seguito di diversi accordi commerciali e variazioni dei prezzi di mercato delle materie le seguenti modifiche devono essere apportate ai prezzi:

a) la materie numero $3$, $12$ e $15$ hanno subito un rincaro del $5$\% rispetto al loro prezzo precedente  
b) le materie con un costo unitario superiore ai $15$ euro ora possono essere acquistate a $12$  
c) tra le prime $10$ materie prime, quelle con costo unitario inferiore a $2$ euro possono essere ottenute gratuitamente  

In [54]:
import numpy as np

costi = np.array([14, 8, 9, 1.2, 6, 0.5, 17, 7.7, 2, 8, 9, 5, 6.70, 22, 3.6, 9.99, 1.55])

print(costi)

[14.    8.    9.    1.2   6.    0.5  17.    7.7   2.    8.    9.    5.
  6.7  22.    3.6   9.99  1.55]


a) Aumento del 5%

In [55]:
# indici: 2, 11, 14
costi[[2, 11, 14]] *= 1.05

print(costi)

[14.    8.    9.45  1.2   6.    0.5  17.    7.7   2.    8.    9.    5.25
  6.7  22.    3.78  9.99  1.55]


b) Prezzi > 15 diventano 12

In [56]:
costi[costi > 15] = 12

print(costi)

[14.    8.    9.45  1.2   6.    0.5  12.    7.7   2.    8.    9.    5.25
  6.7  12.    3.78  9.99  1.55]


c) Primi 10 elementi < 2 diventano 0

In [57]:
costi[:10][costi[:10] < 2] = 0

print(costi)

[14.    8.    9.45  0.    6.    0.   12.    7.7   2.    8.    9.    5.25
  6.7  12.    3.78  9.99  1.55]


# Lavorare con Array multidimensionali

Per definire degli array con piu' dimensioni si utilizza la sintassi che si userebbe per rappresentarli come liste di liste:

* `[ ... ]` vettore 1-dimensionale
* `[[ ... ], [ ... ]]` vettore 2-dimensionale
* `[[[ ... ], .... ], [[ ... ], ... ]]` vettore 3-dimensionale
* e cosi' via

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12], [13, 14, 15]])
print(f'A: \n {A}\n\nshape: {A.shape}')

A: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

shape: (5, 3)


Accesso agli elementi

In [ ]:
print(f'A[0][0]: \n {A[0][0]}\n')
print(f'A[0, 0]: \n {A[0, 0]}\n')
print(f'A[0]: \n {A[0]}') # restituisce la prima riga

A[0][0]: 
 1

A[0, 0]: 
 1

A[0]: 
 [1 2 3]


E' possibile accedere a righe, colonne o parti di esse con l'uso delle slice

In [ ]:
print(f'A[0, :]: \n{A[0, :]}\n')
print(f'A[:, 0]: \n{A[:, 0]}\n')
print(f'A[2:4]: \n{A[2:4]}\n')
print(f'A[:, 1:3]: \n{A[:, 1:3]}\n')
print(f'A[2:4, 1:3]: \n{A[2:4, 1:3]}\n')

A[0, :]: 
[1 2 3]

A[:, 0]: 
[ 1  4  7 10 13]

A[2:4]: 
[[ 7  8  9]
 [10 11 12]]

A[:, 1:3]: 
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]
 [14 15]]

A[2:4, 1:3]: 
[[ 8  9]
 [11 12]]



Anche per gli array multidimensionli le funzioni matematiche viste sopra funzionano allo stesso modo

In [ ]:
A + A

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [ ]:
np.sum(A)

120

Per il prodotto matriciale si puo' utilizzare l'operatore `@`

In [ ]:
x = np.array([0.1, 0.2, 0.3])

In [ ]:
np.matmul(A, x)

array([1.4, 3.2, 5. , 6.8, 8.6])

In [ ]:
A @ x

array([1.4, 3.2, 5. , 6.8, 8.6])

Trasposizione di una matrice e diagonale

In [ ]:
A.T

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [ ]:
np.diag(A)

array([1, 5, 9])

In [ ]:
np.diag(np.diag(A))


array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

## Caratteristiche di un Numpy Array

Creiamo ora un tensore costituito da 3 matrici 2x3

In [ ]:
B = np.array([[[1,2,3], [1,2,3]], [[4,5,6], [4,5,6]], [[7,8,9], [7,8,9]]])

In [ ]:
print(B)

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


Possiamo visualizzare le seguenti caratteristiche dell'array

In [ ]:
print(B.shape)
print(B.dtype)
print(B.ndim)
print(B.size)

(3, 2, 3)
int64
3
18


## Esercizio
Che cosa restituisce `len` quando chiamato su un numpy array?

In [58]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(len(a))
print(len(b))

4
2


## Generare matrici

In [ ]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((5,5),9.0)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Accesso ad elementi con maschere booleane

E' possibile selezionare elementi di un array che verificano una data condizione

In [ ]:
print(A % 2 == 0)

[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]
 [False  True False]]


In [ ]:
A[A % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

E' anche possibile determinare gli indici degli elementi che verificano una data condizione

In [ ]:
np.nonzero(A>2)

(array([0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]),
 array([2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

## Funzioni ed assi

Quando si lavora con array multidimensionali, molte operazioni possono essere eseguite lungo un dato asse (dimensione) dell' array

In [ ]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
np.sum(A, axis=None)

120

In [ ]:
np.sum(A, axis=1)

array([ 6, 15, 24, 33, 42])

In [ ]:
np.sum(A, axis=0)

array([35, 40, 45])

In [ ]:
np.mean(A, axis=0)

array([7., 8., 9.])

In [ ]:
np.mean(A, axis=1)

array([ 2.,  5.,  8., 11., 14.])

# Altre operazioni su array

Modificare la `shape` di un array

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

E' possibile utilizzare `np.newaxis` per aggiungere una dimensione ad un array

In [ ]:
a[np.newaxis, :].shape

(1, 10)

In [ ]:
a[ :, np.newaxis].shape

(10, 1)

Concatenare array con `concatenate`

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

Combinare array con `hstack` e `vstack`

In [ ]:
a = np.array([1,2,3,4])[np.newaxis, :]
b = np.array([5,6,7,8])[np.newaxis, :]

In [ ]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
np.hstack((a.T ,b.T))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack((a.T, b.T))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Generare numeri casuali e campionamento

Generiamo numeri casuali tra 0 ed 1

In [ ]:
np.random.random((3,2))

array([[0.00551398, 0.11279667],
       [0.87761649, 0.27649533],
       [0.88949119, 0.77897704]])

Ora generiamoli da una distribuzione normale

In [ ]:
np.random.randn(3,2)

array([[-1.62142681, -0.6064618 ],
       [-0.34678027,  0.05789511],
       [-1.55042253,  0.15687604]])

In [ ]:
c = np.random.randn(10000)
print(c.mean(), c.var(), c.std())

-0.0028769236161502597 0.9826499305689927 0.9912870071624024


Generiamo casualmente dei numeri interi

In [ ]:
np.random.randint(3,10,size=(3,3))

array([[5, 4, 8],
       [5, 8, 4],
       [3, 3, 5]])

In [ ]:
np.random.randint(20,size=(3,3))

array([[ 1,  1,  3],
       [ 7,  3,  0],
       [15,  0,  5]])

E' anche possibile campionare dei numeri da una sequenza con e senza reinserimento

In [ ]:
np.random.choice(7, replace=False, size=3)

array([3, 1, 5])

In [ ]:
np.random.choice([1,2,3,4], size=8)

array([3, 2, 4, 2, 2, 2, 1, 2])

# Esercizi

## 1. Modificare la funzione obiettivo di un problema di ottimizzazione

Un stabilimento di produzione presenta al suo interno 200 diverse postazioni di lavorazione. Nello stabilimento vengono assemblati 1000 tipi diversi di prodotti. Per ogni prodotto e' noto il tempo di lavorazione (in ore) richiesto in ogni postazione ed il costo all'ora di ogni postazione di lavorazione. Tuttavia, per ridurre i tempi di produzione, l'azienda decide di assegnare le lavorazioni che richiedono piu' di 5 ore ad una ditta esterna ad un costo forfettario di 5 euro per ogni lavorazione.

Modificare il calcolo del costo di produzione ogni prodotto in modo tale da tenere in considerazione questo fatto.

Generiamo casualmente la matrice dei tempi di lavorazione per ogni prodotto ed il costo orario per ogni postazione

In [60]:
import numpy as np

### Dati:

# Tempi[i, j] = Tempo richiesto dal prodotto i nella postazione j
tempi = np.random.uniform(0, 10, (1000, 200))

# Costo orario di ciascuna postazione
costi_orari = np.random.uniform(1, 10, 200)


### Soluzione:

# Calcolo del costo normale
costi = tempi * costi_orari

# Individuo le lavorazioni con tempo maggiore di 5
mask = tempi > 5

# Sostituisco quei costi con 5 euro
costi[mask] = 5

# Costo totale di ogni prodotto
costo_totale = costi.sum(axis=1)
print(costo_totale)

[1833.79409219 1916.12116533 1807.68631399 1885.99497499 1775.16010671
 1777.67312643 1874.73746974 2025.89101197 1859.41456397 1887.05836368
 1979.33827507 2041.87094285 1757.68858345 2045.40939139 1996.95962012
 1887.18299294 1886.77803017 1822.21783137 1791.46791652 1877.42293221
 1831.34744827 1975.69650653 1959.40206629 2053.56927443 2050.94301571
 1778.95229538 1871.88192524 1973.79726542 1856.76152489 2001.53985041
 1991.98408651 1945.31281458 1816.51848147 1974.9225585  1844.79232364
 1890.97631178 1806.06664122 1775.43352752 2140.74870123 1928.66685336
 1732.67629469 1904.7982738  1984.44540208 2100.15071186 1853.6399593
 1775.5316681  2090.23783878 1968.85484818 1812.7210245  1949.516458
 1800.09393582 2002.65649982 1851.58044959 2017.34698168 2000.8652436
 1957.74382143 1959.1901781  2182.553158   1888.06927091 1719.50424247
 1900.46469743 1712.62169576 1948.11944171 2015.30946115 2079.24518722
 1830.80300731 1871.2142053  1957.53789298 1924.85903602 2041.12589007
 2002.6759

## 2. Verificare che una soluzione rispetti i vincoli di un problema lineare

Si ipotizzi che, per un dato problema di programmazione lineare con 10000 variabili vi siano 20000 vincoli. Generare casualmente la matrice ed il vettore che rappresentano i vincoli e poi generare una soluzione per il problema. Verficare se la soluzione rispetta tutti i vincoli.

In [61]:
import numpy as np

### Dati:

# matrice dei vincoli (20000 vincoli, 10000 variabili)
A = np.random.rand(20000, 10000)

# vettore dei termini noti
b = np.random.rand(20000)

# soluzione candidata
x = np.random.rand(10000)


### Soluzione:

# Calcolo del lato sinistro (A x)
lhs = A @ x

# Verifica dei vincoli (A x <= b)
vincoli = lhs <= b

# Verifica se tutti i vincoli sono rispettati
tutti_ok = np.all(vincoli)
print("La soluzione rispetta tutti i vincoli:", tutti_ok)


# Quali vincoli sono violati?
violati = np.where(vincoli == False)[0]
print("Vincoli violati:", violati)

La soluzione rispetta tutti i vincoli: False
Vincoli violati: [    0     1     2 ... 19997 19998 19999]
